// GF(2^8) arithmetic for Reed-Solomon.
// Primitive polynomial: p(x) = x^8 + x^4 + x^3 + x^2 + 1 (0x11D).
//
// Constant-time discipline (Step 20a): the multiply/inverse/divide path is
// **branch-free and table-free** — no data-dependent loads, no value-dependent
// branches. This is required because the RS decoder feeds these functions the
// secret-derived decoded codeword (see docs/SECURITY-AUDIT.md). `gf_mul` is a
// carry-less multiply + fixed reduction; `gf_inv` is a fixed addition chain
// (a^254 = a^{-1}); both treat 0 branchlessly (0 maps to 0).
//
// The precomputed log/antilog tables remain but are used **only on public
// index paths** (generator-poly precompute, syndrome/Chien evaluation indexed
// by public loop counters, and the additive FFT's public basis in Step 20c).
// They are never indexed by a secret in arithmetic any more.

// ── Table generation ──────────────────────────────────────────────────────────
//
// GF(2^8) has 256 elements. The non-zero elements form a cyclic group of
// order 255 generated by α (the root of p(x), i.e. the field element 0x02).
//
// GF_EXP[i] = α^i  for i = 0..254
// GF_LOG[α^i] = i  for i = 0..254  (GF_LOG[0] = 0, sentinel — never read)
//
// The table is doubled (size 512): GF_EXP[i] = GF_EXP[i mod 255].
// This lets gf_mul use GF_EXP[log_a + log_b] without a % 255 reduction,
// since log_a + log_b ≤ 254 + 254 = 508 < 512.

const fn build_tables() -> ([u8; 512], [u8; 256]) {
    let mut exp = [0u8; 512];
    let mut log = [0u8; 256];

    // x tracks the current power of α as a u16 so we can detect the x^8 term
    // without u8 overflow.
    let mut x: u16 = 1;
    let mut i = 0usize;
    while i < 255 {
        exp[i] = x as u8;
        exp[i + 255] = x as u8; // doubled copy
        log[x as usize] = i as u8;

        // Multiply by α = 0x02: left-shift, then reduce if x^8 term appears.
        // Reduction: x^8 ≡ x^4 + x^3 + x^2 + 1 (low 8 bits of 0x11D = 0x1D).
        x <<= 1;
        if x & 0x100 != 0 {
            x ^= 0x11D;
        }

        i += 1;
    }
    // exp[255] was already set above (i=0 wrote exp[0+255]=exp[255]=1).
    // Indices 510 and 511 remain 0 but are never accessed (max sum of two logs
    // is 508).

    (exp, log)
}

const TABLES: ([u8; 512], [u8; 256]) = build_tables();

/// α^i for i = 0..508. GF_EXP[i] == GF_EXP[i mod 255] for i < 510.
pub(crate) const GF_EXP: &[u8; 512] = &TABLES.0;

/// Discrete log base α. GF_LOG[α^i] == i for i in 0..255.
/// GF_LOG[0] is a sentinel (value 0); never pass 0 to functions that use it.
///
/// No longer used by the (now branch-free) arithmetic below — retained for
/// public-index paths only (the additive FFT of Step 20c indexes it by the
/// public FFT basis). `allow(dead_code)` until that lands.
#[allow(dead_code)]
pub(crate) const GF_LOG: &[u8; 256] = &TABLES.1;

// ── Arithmetic ────────────────────────────────────────────────────────────────

/// Addition in GF(2^8) is bitwise XOR.
#[inline(always)]
pub fn gf_add(a: u8, b: u8) -> u8 {
    a ^ b
}

/// Reduce a carry-less product (deg ≤ 14, i.e. a 15-bit polynomial) modulo
/// p(x) = 0x11D, producing an element of GF(2^8) (deg < 8).
///
/// Branch-free: clears bits 14..8 from the top down. Because p(x) has its
/// leading term at bit 8, `0x11D << (k - 8)` has its top bit exactly at bit `k`,
/// so XOR-ing it clears bit `k` without disturbing any higher bit. The shift
/// amount and loop bound are constants; the only data dependence is the masked
/// XOR, which executes regardless of the bit's value.
#[inline(always)]
fn gf_reduce(mut x: u16) -> u8 {
    let mut p: u32 = 14;
    while p >= 8 {
        let bit = (x >> p) & 1;
        let mask = 0u16.wrapping_sub(bit); // 0xFFFF if bit set, else 0x0000
        x ^= mask & (0x011Du16 << (p - 8));
        p -= 1;
    }
    x as u8
}

/// Squaring in GF(2^8). Squaring is F2-linear: interleave zero bits between the
/// input bits, then reduce. Branch-free (no value-dependent control flow).
#[inline(always)]
fn gf_sq(a: u8) -> u8 {
    let a = a as u16;
    let mut spread: u16 = 0;
    let mut i = 0u32;
    while i < 8 {
        let bit = (a >> i) & 1;
        spread |= bit << (2 * i);
        i += 1;
    }
    gf_reduce(spread)
}

/// Multiplication in GF(2^8): branch-free carry-less multiply + reduction.
/// gf_mul(a, b) = (a · b mod p(x)). Zero is handled branchlessly (any masked
/// term with a clear `b` bit contributes nothing; a == 0 ⇒ product 0).
#[inline]
pub fn gf_mul(a: u8, b: u8) -> u8 {
    let a = a as u16;
    let b = b as u16;
    // Carry-less product: prod = XOR over set bits i of b of (a << i).
    // deg(prod) ≤ 7 + 7 = 14, so it fits in u16.
    let mut prod: u16 = 0;
    let mut i = 0u32;
    while i < 8 {
        let bit = (b >> i) & 1;
        let mask = 0u16.wrapping_sub(bit); // 0xFFFF if bit i of b set
        prod ^= mask & (a << i);
        i += 1;
    }
    gf_reduce(prod)
}

/// Multiplicative inverse in GF(2^8) via a fixed addition chain.
/// a^{-1} = a^254 (since a^255 = 1 for a ≠ 0). The chain
/// 2,3,4,7,11,15,30,60,120,127,254 uses only `gf_sq`/`gf_mul`, so it is
/// branch-free and runs the same instructions for every input.
///
/// `gf_inv(0) == 0` (0 has no inverse; this is a branchless sentinel, matching
/// the HQC reference — every square/multiply of 0 stays 0).
#[inline]
pub fn gf_inv(a: u8) -> u8 {
    let a2 = gf_sq(a); // a^2
    let a3 = gf_mul(a2, a); // a^3
    let a4 = gf_sq(a2); // a^4
    let a7 = gf_mul(a4, a3); // a^7
    let a11 = gf_mul(a4, a7); // a^11  = a^4 · a^7
    let a15 = gf_mul(a11, a4); // a^15  = a^11 · a^4
    let a30 = gf_sq(a15); // a^30
    let a60 = gf_sq(a30); // a^60
    let a120 = gf_sq(a60); // a^120
    let a127 = gf_mul(a120, a7); // a^127 = a^120 · a^7
    gf_sq(a127) // a^254 = (a^127)^2
}

/// Division: a / b = a · b^{-1}. Branch-free.
/// `gf_div(a, 0) == 0` (follows from `gf_inv(0) == 0`); `gf_div(0, b) == 0`.
#[inline]
pub fn gf_div(a: u8, b: u8) -> u8 {
    gf_mul(a, gf_inv(b))
}

/// Evaluate polynomial p (coefficients p[0] + p[1]·x + … ) at field element x
/// using Horner's method.
pub fn gf_poly_eval(p: &[u8], x: u8) -> u8 {
    let mut acc = 0u8;
    for &coeff in p.iter().rev() {
        acc = gf_add(gf_mul(acc, x), coeff);
    }
    acc
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Oracles: the old table-based arithmetic (pre-Step-20a) ─────────────────
    // Retained only here to prove the new branch-free `gf_mul`/`gf_inv` produce
    // byte-identical results across the entire input space. (Same cross-check
    // pattern Step 17 used for `mul_dense_ct_bitwise`.)

    /// Old table-based multiply: gf_mul(a,b) = α^(log a + log b), zero special-cased.
    fn gf_mul_table(a: u8, b: u8) -> u8 {
        if a == 0 || b == 0 {
            return 0;
        }
        GF_EXP[GF_LOG[a as usize] as usize + GF_LOG[b as usize] as usize]
    }

    /// Old table-based inverse: a^{-1} = α^{255 - log a} (undefined at 0).
    fn gf_inv_table(a: u8) -> u8 {
        GF_EXP[255 - GF_LOG[a as usize] as usize]
    }

    #[test]
    fn gf_mul_matches_table_oracle_exhaustive() {
        // All 256×256 = 65 536 pairs, including zeros.
        for a in 0u8..=255 {
            for b in 0u8..=255 {
                assert_eq!(gf_mul(a, b), gf_mul_table(a, b), "a={a:#04x} b={b:#04x}");
            }
        }
    }

    #[test]
    fn gf_inv_matches_table_oracle_exhaustive() {
        // Branch-free inverse must match the table for every non-zero element.
        for a in 1u8..=255 {
            assert_eq!(gf_inv(a), gf_inv_table(a), "a={a:#04x}");
        }
    }

    #[test]
    fn gf_inv_zero_is_zero() {
        // Branchless sentinel: 0 has no inverse, the addition chain maps it to 0.
        assert_eq!(gf_inv(0), 0);
        assert_eq!(gf_div(5, 0), 0);
        assert_eq!(gf_div(0, 7), 0);
    }

    #[test]
    fn gf_sq_matches_self_multiply() {
        // gf_sq(a) must equal gf_mul(a, a) for every element.
        for a in 0u8..=255 {
            assert_eq!(gf_sq(a), gf_mul(a, a), "a={a:#04x}");
        }
    }

    #[test]
    fn exp_log_are_inverses() {
        // GF_EXP[GF_LOG[x]] == x for all non-zero x
        for x in 1u8..=255 {
            assert_eq!(GF_EXP[GF_LOG[x as usize] as usize], x, "x={x}");
        }
    }

    #[test]
    fn generator_order_is_255() {
        // α has multiplicative order 255: α^255 == 1, no smaller power does
        assert_eq!(GF_EXP[255], 1);
        for i in 1..255usize {
            assert_ne!(GF_EXP[i], 1, "α^{i} == 1 but order should be 255");
        }
    }

    #[test]
    fn mul_commutativity() {
        // Sample a grid; full 256×256 is only 65 536 iterations — cheap.
        for a in 0u8..=255 {
            for b in 0u8..=255 {
                assert_eq!(gf_mul(a, b), gf_mul(b, a), "a={a} b={b}");
            }
        }
    }

    #[test]
    fn mul_identity_and_zero() {
        for x in 0u8..=255 {
            assert_eq!(gf_mul(1, x), x);
            assert_eq!(gf_mul(0, x), 0);
            assert_eq!(gf_mul(x, 0), 0);
        }
    }

    #[test]
    fn mul_inv_roundtrip() {
        for x in 1u8..=255 {
            assert_eq!(gf_mul(x, gf_inv(x)), 1, "x={x}");
        }
    }

    #[test]
    fn known_values() {
        // α^1 = 0x02  (the generator is just 2)
        assert_eq!(GF_EXP[1], 0x02);
        // α^8 = x^8 mod p(x) = x^4+x^3+x^2+1 = 0x1D
        assert_eq!(GF_EXP[8], 0x1D);
        // α^255 = 1
        assert_eq!(GF_EXP[255], 0x01);
    }

    #[test]
    fn distributivity() {
        // a*(b+c) == a*b + a*c  for a few triples
        let triples = [
            (0x53u8, 0xCAu8, 0x7Fu8),
            (0x01, 0xFF, 0xAB),
            (0x80, 0x80, 0x01),
        ];
        for (a, b, c) in triples {
            let lhs = gf_mul(a, gf_add(b, c));
            let rhs = gf_add(gf_mul(a, b), gf_mul(a, c));
            assert_eq!(lhs, rhs, "a={a:#04x} b={b:#04x} c={c:#04x}");
        }
    }

    // ── gf_div ────────────────────────────────────────────────────────────────

    #[test]
    fn gf_div_zero_numerator() {
        for b in 1u8..=255 {
            assert_eq!(gf_div(0, b), 0, "b={b}");
        }
    }

    #[test]
    fn gf_div_self_is_one() {
        for x in 1u8..=255 {
            assert_eq!(gf_div(x, x), 1, "x={x}");
        }
    }

    #[test]
    fn gf_div_by_one_is_identity() {
        for x in 0u8..=255 {
            assert_eq!(gf_div(x, 1), x, "x={x}");
        }
    }

    // ── gf_poly_eval ──────────────────────────────────────────────────────────

    #[test]
    fn poly_eval_at_zero_is_constant_term() {
        // p(0) = p[0] regardless of higher-degree coefficients (all x^k terms vanish).
        for c in [0u8, 1, 0x42, 0xFF] {
            assert_eq!(gf_poly_eval(&[c], 0), c);
            assert_eq!(gf_poly_eval(&[c, 0x11, 0xAB], 0), c);
        }
    }

    #[test]
    fn poly_eval_linear() {
        // p(x) = a + b·x → evaluates to gf_add(a, gf_mul(b, x)).
        let cases = [(0u8, 1u8, 2u8), (0x53, 0xCA, 0x7F), (1, 0, 5), (0, 1, 255)];
        for (a, b, x) in cases {
            assert_eq!(
                gf_poly_eval(&[a, b], x),
                gf_add(a, gf_mul(b, x)),
                "a={a} b={b} x={x}"
            );
        }
    }

    #[test]
    fn poly_eval_known_value() {
        // p(x) = 1 + x + x^2, little-endian coefficients [1, 1, 1].
        // p(α) = 1 XOR α XOR α^2 = 1 XOR 2 XOR 4 = 7.
        assert_eq!(gf_poly_eval(&[1, 1, 1], GF_EXP[1]), 7);
    }

    #[test]
    fn poly_eval_root() {
        // (x + α) has coefficients [α, 1] (constant=α, linear=1) in little-endian.
        // In char 2 this equals (x − α), so α must be a root: p(α) = 0.
        let alpha = GF_EXP[1];
        assert_eq!(gf_poly_eval(&[alpha, 1], alpha), 0);
    }
}
